/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Episode {
  id: string;
  title: string;
  description: string;
  duration: string;
  episode_number?: number | null;
  release_date?: string | null;
  spotify_url?: string | null;
  audio_url?: string | null;
}

export interface EpisodesResponse {
  episodes: Episode[];
  source: string;
}

export interface NewsletterSubscribeRequest {
  email: string;
  first_name?: string | null;
}

export interface NewsletterSubscribeResponse {
  message: string;
  status: string;
}

export interface NewsletterError {
  detail: string;
}

export type GetEpisodesParams = {
  limit?: number;
};
