/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * Returns the latest episodes from the Spotify show feed
 * @summary Get latest episodes
 */
export declare const getEpisodesQueryLimitDefault = 6;
export declare const GetEpisodesQueryParams: zod.ZodObject<{
    limit: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    limit: number;
}, {
    limit?: number | undefined;
}>;
export declare const GetEpisodesResponse: zod.ZodObject<{
    episodes: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodString;
        title: zod.ZodString;
        description: zod.ZodString;
        duration: zod.ZodString;
        episode_number: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
        release_date: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        spotify_url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
        audio_url: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    }, "strip", zod.ZodTypeAny, {
        id: string;
        title: string;
        description: string;
        duration: string;
        episode_number?: number | null | undefined;
        release_date?: string | null | undefined;
        spotify_url?: string | null | undefined;
        audio_url?: string | null | undefined;
    }, {
        id: string;
        title: string;
        description: string;
        duration: string;
        episode_number?: number | null | undefined;
        release_date?: string | null | undefined;
        spotify_url?: string | null | undefined;
        audio_url?: string | null | undefined;
    }>, "many">;
    source: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    episodes: {
        id: string;
        title: string;
        description: string;
        duration: string;
        episode_number?: number | null | undefined;
        release_date?: string | null | undefined;
        spotify_url?: string | null | undefined;
        audio_url?: string | null | undefined;
    }[];
    source: string;
}, {
    episodes: {
        id: string;
        title: string;
        description: string;
        duration: string;
        episode_number?: number | null | undefined;
        release_date?: string | null | undefined;
        spotify_url?: string | null | undefined;
        audio_url?: string | null | undefined;
    }[];
    source: string;
}>;
/**
 * Adds an email address to the Mailchimp audience
 * @summary Subscribe to newsletter
 */
export declare const SubscribeNewsletterBody: zod.ZodObject<{
    email: zod.ZodString;
    first_name: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
}, "strip", zod.ZodTypeAny, {
    email: string;
    first_name?: string | null | undefined;
}, {
    email: string;
    first_name?: string | null | undefined;
}>;
export declare const SubscribeNewsletterResponse: zod.ZodObject<{
    message: zod.ZodString;
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
    message: string;
}, {
    status: string;
    message: string;
}>;
//# sourceMappingURL=api.d.ts.map