/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Returns the latest episodes from the Spotify show feed
 * @summary Get latest episodes
 */
export const getEpisodesQueryLimitDefault = 6;

export const GetEpisodesQueryParams = zod.object({
  limit: zod.coerce.number().default(getEpisodesQueryLimitDefault),
});

export const GetEpisodesResponse = zod.object({
  episodes: zod.array(
    zod.object({
      id: zod.string(),
      title: zod.string(),
      description: zod.string(),
      duration: zod.string(),
      episode_number: zod.number().nullish(),
      release_date: zod.string().nullish(),
      spotify_url: zod.string().nullish(),
      audio_url: zod.string().nullish(),
    }),
  ),
  source: zod.string(),
});

/**
 * Adds an email address to the Mailchimp audience
 * @summary Subscribe to newsletter
 */
export const SubscribeNewsletterBody = zod.object({
  email: zod.string().email(),
  first_name: zod.string().nullish(),
});

export const SubscribeNewsletterResponse = zod.object({
  message: zod.string(),
  status: zod.string(),
});
