/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface Episode {
    id: string;
    title: string;
    description: string;
    duration: string;
    episode_number?: number | null;
    release_date?: string | null;
    spotify_url?: string | null;
    audio_url?: string | null;
}
//# sourceMappingURL=episode.d.ts.map